# start the fleet-telemetry server
# hadolint ignore=DL3006
FROM gcr.io/distroless/cc-debian11
WORKDIR /

COPY --from=tesla/fleet-telemetry /go/bin/fleet-telemetry /

CMD ["/fleet-telemetry", "-config", "/fleet-telemetry/config/config.json"]
